version: "3.9"
services:
  mysqldb:
    # image:
    build: ./mysql
    command: --lower_case_table_names=1
    container_name: mysqlcontainer
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: agel
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # lower_case_table_names: 1

  agelbackend:
    build: ./nodejs
    depends_on:
      - mysqldb
    ports:
      - 3125:3125
    volumes:
      - ./nodejs:/app
      - "/app/node_modules"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_NAME=agel
      - DB_PORT=3306
    stdin_open: true
    tty: true
